name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: zayka
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: zayka
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U zayka"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # .github/workflows/ci.yml 

      - name: Install project (+dev)
        run: pip install '.[dev]'        # ← кавычки обязательны

      - name: Ruff lint
        run: ruff check .

      - name: Black check
        run: black --check .

      - name: Run pytest
        env:
          POSTGRES_DSN: postgresql://zayka:secret@localhost:5432/zayka
        run: pytest -q
