name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: zayka
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: zayka
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U zayka"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project (+dev extras)
        run: pip install '.[dev]'

      # ─── Ruff: предупреждает, но не валит CI ───
      - name: Ruff lint (non-blocking)
        run: |
          ruff check . || echo "::warning ::Ruff found issues (see log above)"

      # ─── Black: тоже только предупреждение ───
      - name: Black format check (non-blocking)
        run: |
          black --check . || echo "::warning ::Black would reformat files (see log above)"

      - name: Run pytest
        env:
          POSTGRES_DSN: postgresql://zayka:secret@localhost:5432/zayka
        run: pytest -q
